version: "3.8"

services:
  db:
    image: postgres:alpine
    environment:
    - POSTGRES_DB: demo
    - POSTGRES_USER: postgres
    - POSTGRES_PASSWORD: postgres
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  asynqmon:
    image: hibiken/asynqmon
    ports:
    - 8080:8080
    environment:
    - PORT: 8080
    - REDIS_ADDR: redis
    - REDIS_DB: 0
    # - REDIS_PASSWORD:
  app:
    build: .
    command: go run main.go
    ports:
    - 8000:8000
    volumes:
      - ./:/app
    environment:
      - REDIS_URL: redis:6379
      - DB_URL: postgres://postgres:postgres@db:5432/demo?ssl_mode=disable
    