// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package database

import (
	"database/sql"
)

type Author struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Bio       string       `json:"bio"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Book struct {
	ID        int32         `json:"id"`
	Title     string        `json:"title"`
	AuthorID  sql.NullInt32 `json:"author_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}
